
title: Lawrence Barriner II's CV
url: 'http://lawrencebarrinerii.com'
baseurl: '/online-cv' #change it according to your repository name


# Enable one of these styles by removing #. Style will be applied only after restarting the build or serve.
#style: styles-2
#style: styles-3
#style: styles-4
#style: styles-5
#style: styles-6


#Profile information
name: Lawrence Barriner II
tagline: Communications and Narrative Strategist
pic: profile.png  #place a 100x100 picture inside /assets/images/ folder and provide the name of the file below

#sidebar links
email: lqb@alum.mit.edu
phone: 850.443.5020
website: lawrencebarrinerii.com #do not add http://
linkedin: lawrencebarrinerii
github: lqb2
twitter: '@lqb2'
soundcloud: lawrence-barriner-ii


# Tracker
analytics: UA-86130890-5
#Update all the sections by editing the files inside _includes folder.
